# Iberdrola Datathon: Central Configuration File

[download_execution]
# Steps: ["all"] or list like ["roads", "traffic"]
# Order: roads, traffic, vehicle_registrations, chargers, electric_capacity, gas_stations
steps = ["all"]
force = false

[process_execution]
# Available steps: chargers, vehicle_registrations, gas_stations, electric_capacity, traffic, segments, proximity, gas_stations_proximity
steps = ["electric_capacity", "traffic"]
force = true

# ==========================================
# STEP DEFINITIONS (Processing Parameters)
# ==========================================

[steps.roads]
# Acquisition details moved to download.py

[steps.traffic]
# Data sources
raw_dir = "data/raw/traffic/informacion_tramo"
output_path = "data/standardized/traffic.parquet"
depends_on = []

[steps.vehicle_registrations]
# Acquisition parameters
ano_inicio = 2015
mes_inicio = 1
ano_fin = 2025
mes_fin = 12
# Paths
raw_dir = "data/raw/vehicle_registrations"
output_path = "data/standardized/vehicle_registrations.parquet"
depends_on = []

[steps.chargers]
raw_path = "data/raw/chargers/chargers.xml"
output_path = "data/standardized/chargers.parquet"
depends_on = []

[steps.electric_capacity]
raw_dir = "data/raw/electric_capacity"
output_path = "data/standardized/electric_capacity.parquet"
files = { Endesa = "Endesa_2026_04_01.xlsx", Iberdrola = "Iberdrola_2026_04_01.xlsx", Viesgo = "Viesgo_2026_04_01.xlsx" }
depends_on = []

[steps.gas_stations]
raw_path = "data/raw/gas_stations/gas_stations.json"
output_path = "data/standardized/gas_stations.parquet"
depends_on = []

[steps.segments]
shp_path = "data/raw/traffic/geometria/Geometria_tramos.shp"
traffic_path = "data/standardized/traffic.parquet"
kmz_path = "data/raw/roads/roads.kmz"
output_path = "data/processed/integrated_road_network.parquet"
backbone_output_path = "data/processed/backbone_roads.parquet"
small_segment_length_m = 2000
depends_on = ["data/standardized/traffic.parquet"]

[steps.proximity]
charging_points_path = "data/standardized/chargers.parquet"
road_network_path = "data/processed/integrated_road_network.parquet"
backbone_roads_path = "data/processed/backbone_roads.parquet"
output_path = "data/processed/charging_stations.parquet"
max_distance = 1000
depends_on = ["data/standardized/chargers.parquet", "data/processed/integrated_road_network.parquet", "data/processed/backbone_roads.parquet"]

[steps.gas_stations_proximity]
raw_path = "data/standardized/gas_stations.parquet"
road_network_path = "data/processed/integrated_road_network.parquet"
backbone_roads_path = "data/processed/backbone_roads.parquet"
output_path = "data/processed/gas_stations_proximity.parquet"
max_distance = 1000
depends_on = ["data/standardized/gas_stations.parquet", "data/processed/integrated_road_network.parquet", "data/processed/backbone_roads.parquet"]
